FROM quay.io/pypa/manylinux_2_28_x86_64

# Install GCC 13 Toolset and CUDA 13.3 Core Components
RUN yum install -y yum-utils && \
    yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo && \
    yum install -y gcc-toolset-13-gcc gcc-toolset-13-gcc-c++ \
                   cuda-nvcc-13-3 cuda-cudart-devel-13-3 cuda-libraries-devel-13-3

# Install Ninja build system
RUN yum install -y ninja-build

# SET THE ENVIRONMENT
ENV TOOLSET_BIN=/opt/rh/gcc-toolset-13/root/usr/bin
ENV CUDA_BIN=/usr/local/cuda-13.3/bin

ENV PATH="${TOOLSET_BIN}:${CUDA_BIN}:${PATH}"

# Force compilers to the ones in the toolset
ENV CC="${TOOLSET_BIN}/gcc"
ENV CXX="${TOOLSET_BIN}/g++"
ENV CUDAHOSTCXX="${TOOLSET_BIN}/g++"

# Library paths
ENV LD_LIBRARY_PATH="/usr/local/cuda-13.3/lib64:${LD_LIBRARY_PATH}"
