from collections import deque
import re
import numpy as np
import bpy


def jet_colormap(t: float) -> tuple[float, float, float, float]:
    """Maps normalized value t in [0.0, 1.0] to RGBA tuple using Jet colormap."""
    t = float(np.clip(t, 0.0, 1.0))
    r = float(np.clip(1.5 - abs(4.0 * t - 3.0), 0.0, 1.0))
    g = float(np.clip(1.5 - abs(4.0 * t - 2.0), 0.0, 1.0))
    b = float(np.clip(1.5 - abs(4.0 * t - 1.0), 0.0, 1.0))
    return (r, g, b, 1.0)


def get_or_create_level_material(
    level: int, max_level: int, pass_type: str = "Jet"
) -> bpy.types.Material:
    """Creates an emission material for a specific BVH level mapped via Jet colormap."""
    mat_name = f"BVH_{pass_type}_Level_{level}"
    mat = bpy.data.materials.get(mat_name)
    if not mat:
        mat = bpy.data.materials.new(name=mat_name)

    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    norm_lvl = (level / max_level) if max_level > 0 else 0.0
    r, g, b, a = jet_colormap(norm_lvl)

    emission = nodes.new(type="ShaderNodeEmission")
    emission.inputs["Color"].default_value = (r, g, b, a)
    emission.inputs["Strength"].default_value = 1.0

    output = nodes.new(type="ShaderNodeOutputMaterial")
    links.new(emission.outputs["Emission"], output.inputs["Surface"])

    return mat


def parse_bvh_dot(dot_str: str):
    """Parses Graphviz .dot string generated by forward or backward pass dump().

    Returns:
        nodes: Dict[str, dict] containing 'min', 'max', and 'type' for each N/L node.
        adj: Dict[str, List[str]] directed adjacency list.
        root_id: Key of the root node ('N0' or 'L0').
    """
    nodes = {}
    adj = {}

    node_pattern = re.compile(
        r'(?P<id>[NL]\d+)\s*\[shape=none,\s*label=<\s*<TABLE.*?</TABLE>>\];',
        re.DOTALL,
    )

    float_re = r'([-\d.eE+]+)'
    aabb_min_pattern = re.compile(
        rf'AABB Min:\s*\(\s*{float_re}\s*,\s*{float_re}\s*,\s*{float_re}\s*\)'
    )
    aabb_max_pattern = re.compile(
        rf'AABB Max:\s*\(\s*{float_re}\s*,\s*{float_re}\s*,\s*{float_re}\s*\)'
    )

    for match in node_pattern.finditer(dot_str):
        node_id = match.group('id')
        block = match.group(0)

        min_m = aabb_min_pattern.search(block)
        max_m = aabb_max_pattern.search(block)

        if min_m and max_m:
            min_b = [float(min_m.group(i)) for i in range(1, 4)]
            max_b = [float(max_m.group(i)) for i in range(1, 4)]

            nodes[node_id] = {
                'min': min_b,
                'max': max_b,
                'type': 'LEAF' if node_id.startswith('L') else 'NODE',
            }

    edge_pattern = re.compile(r'(?P<src>N\d+)\s*->\s*(?P<dst>[NL]\d+)')
    for match in edge_pattern.finditer(dot_str):
        src = match.group('src')
        dst = match.group('dst')
        if src not in adj:
            adj[src] = []
        adj[src].append(dst)

    if 'N0' in nodes:
        root_id = 'N0'
    elif 'L0' in nodes:
        root_id = 'L0'
    else:
        root_id = next(iter(nodes.keys())) if nodes else None

    return nodes, adj, root_id


def build_bvh_wireframe_mesh(
    nodes: dict,
    adj: dict,
    root_id: str,
    obj_name: str = "BVH8_Pass",
    pass_type: str = "Jet",
) -> bpy.types.Object:
    """Builds a renderable BVH wireframe mesh object with per-level material slots

    and a Wireframe Modifier.
    """
    if not nodes or not root_id:
        return None

    # Compute BFS depths for each node
    levels = {}
    queue = deque([(root_id, 0)])
    max_level = 0

    while queue:
        curr, lvl = queue.popleft()
        if curr in levels:
            continue
        levels[curr] = lvl
        max_level = max(max_level, lvl)

        for child in adj.get(curr, []):
            if child in nodes and child not in levels:
                queue.append((child, lvl + 1))

    cube_verts = np.array(
        [
            [0, 0, 0],
            [1, 0, 0],
            [1, 1, 0],
            [0, 1, 0],  # Bottom 4
            [0, 0, 1],
            [1, 0, 1],
            [1, 1, 1],
            [0, 1, 1],  # Top 4
        ],
        dtype=np.float32,
    )

    cube_faces = np.array(
        [
            [0, 3, 2, 1],  # Bottom (-Z)
            [4, 5, 6, 7],  # Top (+Z)
            [0, 1, 5, 4],  # Front (-Y)
            [1, 2, 6, 5],  # Right (+X)
            [2, 3, 7, 6],  # Back (+Y)
            [3, 0, 4, 7],  # Left (-X)
        ],
        dtype=np.int32,
    )

    all_verts = []
    all_faces = []
    face_level_indices = []

    vert_offset = 0
    overall_min = np.array([float('inf')] * 3)
    overall_max = np.array([float('-inf')] * 3)

    for node_id, data in nodes.items():
        min_b = np.array(data['min'], dtype=np.float32)
        max_b = np.array(data['max'], dtype=np.float32)
        extent = max_b - min_b

        overall_min = np.minimum(overall_min, min_b)
        overall_max = np.maximum(overall_max, max_b)

        box_verts = min_b + cube_verts * extent
        box_faces = cube_faces + vert_offset

        all_verts.append(box_verts)
        all_faces.append(box_faces)

        lvl = levels.get(node_id, 0)
        face_level_indices.extend([lvl] * 6)
        vert_offset += 8

    verts_concat = np.vstack(all_verts).tolist()
    faces_concat = np.vstack(all_faces).tolist()

    mesh = bpy.data.meshes.new(f"{obj_name}_Mesh")
    mesh.from_pydata(verts_concat, [], faces_concat)
    mesh.update()

    existing_obj = bpy.data.objects.get(obj_name)
    if existing_obj:
        bpy.data.objects.remove(existing_obj, do_unlink=True)

    obj = bpy.data.objects.new(obj_name, mesh)
    bpy.context.collection.objects.link(obj)

    # Assign per-level Jet materials
    for lvl in range(max_level + 1):
        mat = get_or_create_level_material(lvl, max_level, pass_type=pass_type)
        obj.data.materials.append(mat)

    for poly_idx, lvl_idx in enumerate(face_level_indices):
        mesh.polygons[poly_idx].material_index = lvl_idx

    # Apply Wireframe Modifier
    scene_extent = np.linalg.norm(overall_max - overall_min)
    wire_thickness = max(scene_extent * 0.0015, 0.001)

    wire_mod = obj.modifiers.new(name="BVH_Wireframe", type='WIREFRAME')
    wire_mod.thickness = wire_thickness
    wire_mod.use_replace = True
    wire_mod.use_even_offset = True
    wire_mod.material_offset = 0

    return obj
